baseURL: https://www.tzyi.dev
languageCode: en-us
title: TZYI
theme: "PaperMod"
pluralizelisttitles: false
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

staticDir:
    - static

menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: about
      name: about
      url: /who/about
      weight: 1
    # - identifier: archives
    #   name: archive
    #   url: /archives/
    #   weight: 21
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30

params:
  ShowBreadCrumbs: true
  # ShowShareButtons: true
  defaultTheme: auto
  ShowFullTextinRSS: true

  # working home-info mode
  homeInfoParams:
    Title: "Join us as we make wee wonderful games"
    Content: >
            Hello, we are TzYi, an indie game developer based in the UK.  
            We're making a wee wonderful **turn based strategy** game based on **celtic mythology.**
            
            - Please bookmark us and follow us on [social media](https://www.instagram.com/tzyi.dev/) to be first to learn of all the secrets about our new game! 

  
  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/tzyi.dev/"
    - name: "rss"
      url: "https://www.tzyi.dev/index.xml"
    # - name: twitter
    #   url: "https://instagram.com"
    # - name: itchio
    #   url: "https://instagram.com"

# Working profile mode if we need it
# params:
#   profileMode:
#       enabled: true
#       title: "Titltle" # optional default will be site title
#       subtitle: "This is subtitle"
#       imageUrl: "/test256.jpg" # optional
#       imageTitle: "hellos" # optional
#       imageWidth: 120 # custom size
#       imageHeight: 120 # custom size
#       buttons:
#           - name: Archive
#             url: "/archives/"
#           - name: Github
#             url: "https://github.com/"

#   socialIcons: # optional
#       - name: instagram
#         url: "https://github.com/"
#       - name: itchio
#         url: "https://github.com/"
